services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: events_user
      POSTGRES_PASSWORD: password_db
      POSTGRES_DB: events
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: