[project]
name = "events-aggregator"
version = "0.1.0"
description = "backend-агрегатор событий"
readme = "README.md"
authors = [
    { name = "Aleksander Karmanov", email = "karmanov.aleks2016@yandex.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
events-aggregator = "events_aggregator:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.4",
]
